[package]
name = "data-sync-tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
fake = {version = "2.5", features=['derive', 'chrono', 'uuid', ]}
mockall = "0.11.3"
rand = "0.8.5"
readonly = "0.2.3"
uuid = "1.3.0"
